const fs=require('fs'),path=require('path');
const root=process.cwd(),src=path.join(root,'index.html'),out=path.join(root,'public');
let html=fs.readFileSync(src,'utf8');
const marker='/* ORGANIZER_AI_COMMANDS_V3 */';
if(!html.includes(marker)){
const code=String.raw`<script>
${marker}
(function(){
const esc3=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const key='our_app_data_v1';
function read(){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch(e){return {}}}
function write(d){localStorage.setItem(key,JSON.stringify(d));if(typeof render==='function')render();if(typeof scheduleNotifications==='function')scheduleNotifications()}
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function apply(actions){const d=read();d.plans=d.plans||[];d.bills=d.bills||[];d.pays=d.pays||[];d.recipes=d.recipes||[];d.us=d.us||[];d.captures=d.captures||[];d.billTransactions=d.billTransactions||[];d.billAccount=Number(d.billAccount||0);for(const a of actions||[]){if(a.type==='add_reminder'&&a.name&&a.date)d.plans.push({name:String(a.name),date:String(a.date),time:String(a.time||''),reminder:true,source:'AI Command'});else if(a.type==='delete_reminder'&&a.query){const q=String(a.query).toLowerCase(),i=d.plans.findIndex(x=>String(x.name||'').toLowerCase().includes(q));if(i>=0)d.plans.splice(i,1)}else if(a.type==='add_bill'&&a.name)d.bills.push({name:String(a.name),amount:Number(a.amount||0),date:String(a.date||''),freq:String(a.freq||'Monthly')});else if(a.type==='add_pay')d.pays.unshift({amount:Number(a.amount||0),date:String(a.date||today())});else if(a.type==='add_note')d.us.push({cat:'Notes',title:String(a.title||'Note'),text:String(a.text||''),date:new Date().toLocaleDateString(),image:String(a.image||'')});else if(a.type==='add_recipe')d.recipes.push({name:String(a.name||'Untitled recipe'),link:String(a.link||''),notes:String(a.notes||''),image:String(a.image||''),date:new Date().toLocaleDateString(),source:'AI Command'});else if(a.type==='add_bill_money'){const n=Number(a.amount||0);if(n>0){d.billAccount+=a.direction==='remove'?-n:n;d.billAccount=Math.max(0,d.billAccount);d.billTransactions.push({type:a.direction==='remove'?'remove':'add',amount:n,date:new Date().toISOString(),source:'AI Command'})}}else if(a.type==='save_capture')d.captures.push({title:String(a.title||'Unsorted capture'),category:String(a.category||'other'),summary:String(a.summary||''),suggestedDestination:String(a.suggestedDestination||'Inbox'),text:String(a.text||''),image:String(a.image||''),date:new Date().toLocaleDateString(),source:'Quick Capture'});}write(d)}
function statusBox(){let b=document.getElementById('commandStatus');if(!b){b=document.createElement('div');b.id='commandStatus';b.className='ai-preview';document.getElementById('modalBody')?.appendChild(b)}b.style.display='block';return b}
function closeAndShow(id){try{closeModal()}catch(e){}if(typeof show==='function')show(id)}
async function imageData(file){return new Promise((ok,bad)=>{if(!file)return ok('');const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=bad;r.readAsDataURL(file)})}
async function runCapture(text,image,status){
status.innerHTML='<b>OUR AI</b><div>Figuring out where this belongs…</div>';
let ai=null;
if(image){try{const r=await fetch('/api/capture-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,text})});if(r.ok)ai=await r.json()}catch(e){}}
if(text){try{const r=await fetch('/api/organizer-command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,data:read(),today:today(),image})});const out=await r.json();if(r.ok&&Array.isArray(out.actions)&&out.actions.length){apply(out.actions);status.innerHTML='<b>Done</b><div>'+esc3(out.reply||'Saved in the right place.')+'</div>';setTimeout(()=>closeAndShow(out.actions.some(a=>a.type==='add_bill_money'||a.type==='add_bill'||a.type==='add_pay')?'money':out.actions.some(a=>a.type==='add_note')?'notes':out.actions.some(a=>a.type==='add_recipe')?'recipes':'plan'),250);return}}catch(e){}}
if(ai){const dest=String(ai.suggestedDestination||'').toLowerCase(),cat=String(ai.category||'').toLowerCase(),d=read();d.us=d.us||[];d.recipes=d.recipes||[];d.captures=d.captures||[];if(cat==='recipe'||dest.includes('recipe')){d.recipes.push({name:String(ai.title||'Captured recipe'),link:'',notes:String(ai.summary||text),image,date:new Date().toLocaleDateString(),source:'Quick Capture'});write(d);status.innerHTML='<b>Saved to Recipes</b><div>'+esc3(ai.summary||'Recipe saved.')+'</div>';setTimeout(()=>closeAndShow('recipes'),250);return}if(dest.includes('note')){d.us.push({cat:'Notes',title:String(ai.title||text||'Note'),text:String(text||ai.summary||''),date:new Date().toLocaleDateString(),image});write(d);status.innerHTML='<b>Saved to Notes & Ideas</b><div>'+esc3(ai.summary||'Saved.')+'</div>';setTimeout(()=>closeAndShow('notes'),250);return}d.captures.push({title:String(ai.title||text||'Unsorted capture'),category:String(ai.category||'other'),summary:String(ai.summary||'Saved safely.'),suggestedDestination:String(ai.suggestedDestination||'Inbox'),extractedText:String(ai.extractedText||''),text,image,date:new Date().toLocaleDateString(),source:'Quick Capture'});write(d);status.innerHTML='<b>Saved to Quick Capture</b><div>'+esc3(ai.summary||'The capture was saved safely.')+'</div>';setTimeout(()=>closeAndShow('notes'),250);return}
const d=read();d.captures=d.captures||[];d.captures.push({title:text||'Unsorted capture',category:'other',summary:'Saved safely to Quick Capture.',suggestedDestination:'Inbox',text,image,date:new Date().toLocaleDateString(),source:'Quick Capture'});write(d);status.innerHTML='<b>Saved safely</b><div>Nothing was lost. It is in Quick Capture.</div>';setTimeout(()=>closeAndShow('notes'),250)
}
function intercept(ev){const btn=ev.target&&ev.target.closest?ev.target.closest('#modalSave'):null;if(!btn)return;const title=document.getElementById('modalTitle');if(!title||title.textContent.trim().toLowerCase()!=='quick capture')return;ev.preventDefault();ev.stopImmediatePropagation();const body=document.getElementById('modalBody'),text=body?.querySelector('textarea')?.value?.trim()||'',file=body?.querySelector('#captureFile')?.files?.[0];if(!text&&!file)return alert('Add something first.');statusBox();imageData(file).then(image=>runCapture(text,image,statusBox())).catch(()=>runCapture(text,'',statusBox()))}
document.addEventListener('click',intercept,true);
})();
</script>`;
const i=html.toLowerCase().lastIndexOf('</body>');if(i===-1)throw new Error('Missing body');html=html.slice(0,i)+code+html.slice(i)}
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.copyFileSync(src,path.join(out,'index.html'));for(const name of ['manifest.webmanifest','sw.js']){const p=path.join(root,name);if(fs.existsSync(p))fs.copyFileSync(p,path.join(out,name))}console.log('Build complete: Quick Capture V3 enabled');
