self.addEventListener('install',e=>e.waitUntil(self.skipWaiting()));
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));

const BOOT = `<script>(function(){try{const K='our_app_data_v1',d=JSON.parse(localStorage.getItem(K)||'null');if(!d||typeof d!=='object')throw 0;['plans','bills','pays','recipes','us','bike','folders'].forEach(k=>{if(!Array.isArray(d[k]))d[k]=[]});d.goal=Number(d.goal)||0;localStorage.setItem(K,JSON.stringify(d))}catch(e){localStorage.setItem('our_app_data_v1',JSON.stringify({plans:[],bills:[],pays:[],recipes:[],us:[],bike:[],folders:[],goal:0}))}})();</script>`;
const CAL = `<script>(function(){function pad(n){return String(n).padStart(2,'0')}function key(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}function esc(s){return String(s??'').replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]))}function draw(){const card=document.getElementById('todayCard');if(!card||typeof data==='undefined')return;const start=new Date();start.setHours(0,0,0,0);const days=[0,1,2].map(i=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});card.innerHTML='<div class=\\"three-day-calendar\\">'+days.map((d,i)=>{const plans=(data.plans||[]).filter(p=>p.date===key(d));return '<button type=\\"button\\" class=\\"day-column '+(i===0?'today':'')+'\\" onclick=\\"show(\\\\'plan\\\\')\\"><div class=\\"day-name\\">'+d.toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()+'</div><div class=\\"day-number\\">'+d.getDate()+'</div>'+(plans.length?'<div class=\\"day-items\\">'+plans.slice(0,3).map(p=>'<div class=\\"day-item\\">'+esc(p.text)+'</div>').join('')+(plans.length>3?'<div class=\\"day-more\\">+'+(plans.length-3)+' more</div>':'')+'</div>':'<div class=\\"day-empty\\">Nothing planned</div>')+'</button>'}).join('')+'</div>'}const s=document.createElement('style');s.textContent='.three-day-calendar{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.day-column{appearance:none;border:1px solid #ffffff10;background:#17171b;color:#fff;border-radius:15px;padding:11px 7px;min-width:0;text-align:left}.day-column.today{border-color:#ff202855;background:#1d1113}.day-name{font-size:11px;font-weight:850;letter-spacing:.08em;color:#aaa;text-align:center}.day-column.today .day-name{color:#ff6268}.day-number{font-size:25px;font-weight:850;text-align:center;margin:3px 0 9px}.day-items{min-height:48px}.day-item{font-size:11px;line-height:1.25;background:#222227;border-radius:8px;padding:6px;margin-top:5px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.day-more{font-size:10px;color:#999;margin-top:5px;text-align:center}.day-empty{font-size:10px;color:#777;text-align:center;line-height:1.25;min-height:48px;display:grid;place-items:center}.day-column:active{transform:scale(.98)}';document.head.appendChild(s);if(typeof window.render==='function'){const base=window.render;window.render=function(){base();draw()};draw()}})();</script>`;
const RECIPE_FIX = `<script>(function(){function wire(){const list=document.getElementById('recipeList');if(!list)return;list.querySelectorAll('.recipe-item').forEach((el,i)=>{el.setAttribute('role','button');el.setAttribute('tabindex','0');el.style.cursor='pointer';el.addEventListener('pointerup',function(e){if(e.target.closest('button,a,input'))return;e.preventDefault();if(typeof window.openRecipeDetail==='function')window.openRecipeDetail(i)},{passive:false});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();if(typeof window.openRecipeDetail==='function')window.openRecipeDetail(i)}})})}function install(){if(typeof window.render==='function'&&!window.__recipeWire){const base=window.render;window.render=function(){base();wire()};window.__recipeWire=true}wire()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install()})();</script>`;
const RECIPE_DESIGN = `<script>(function(){function style(){if(document.getElementById('recipeDetailStyle'))return;const s=document.createElement('style');s.id='recipeDetailStyle';s.textContent='.recipe-detail-wrap{display:block}.recipe-detail-hero{display:grid;grid-template-columns:116px 1fr;gap:15px;align-items:start;margin:8px 0 18px}.recipe-detail-hero img.recipe-detail-img{width:116px;height:116px;max-height:none;object-fit:cover;border-radius:18px;margin:0}.recipe-detail-title{font-size:28px;line-height:1.05;margin:0 0 10px;font-weight:850}.recipe-detail-meta{color:#999;font-size:13px;line-height:1.8}.recipe-detail-meta span{display:block}.recipe-detail-section{background:linear-gradient(145deg,#151518,#0e0e11);border:1px solid #ffffff10;border-radius:18px;padding:16px;margin:10px 0}.recipe-detail-section h3{margin:0 0 10px;font-size:18px}.recipe-detail-section p{margin:0;color:#ddd;line-height:1.55}.recipe-source{display:flex;align-items:center;justify-content:space-between;gap:12px}.recipe-source button{white-space:nowrap}.recipe-detail-smallshot{width:100%;max-height:240px;object-fit:contain;border-radius:14px;background:#050506;margin-top:10px}.recipe-detail-hero+*{}';document.head.appendChild(s)}function compact(){style();const mb=document.getElementById('mb');if(!mb)return;const img=mb.querySelector('img.recipe-detail-img');if(!img)return;if(mb.dataset.compact==='1')return;mb.dataset.compact='1';const all=Array.from(mb.children);if(!all.length)return;const wrap=document.createElement('div');wrap.className='recipe-detail-wrap';const hero=document.createElement('div');hero.className='recipe-detail-hero';const heroImg=img.cloneNode(true);heroImg.className='recipe-detail-img';hero.appendChild(heroImg);const rest=document.createElement('div');rest.innerHTML=all.filter(x=>x!==img).map(x=>x.outerHTML||'').join('');hero.appendChild(rest);mb.innerHTML='';mb.appendChild(hero);const source=document.createElement('div');source.className='recipe-detail-section';source.innerHTML='<h3>Source</h3><div class=\\"recipe-source\\"><span>📷 Original screenshot</span><button class=\\"btn dark\\" type=\\"button\\" id=\\"viewRecipeScreenshot\\">View screenshot</button></div>';mb.appendChild(source);document.getElementById('viewRecipeScreenshot').onclick=function(){const src=heroImg.src;openModal('Original Screenshot','<img class=\\"recipe-detail-smallshot\\" src=\\"'+src+'\\">')};}function install(){const old=window.openRecipeDetail;if(typeof old==='function'&&!window.__recipeDesign){window.openRecipeDetail=function(i){old(i);setTimeout(compact,30)};window.__recipeDesign=true}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setInterval(install,500)})();</script>`;
const AI_RECIPE = `<script>(function(){
function esc(s){return String(s??'').replace(/[&<>\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[m]))}
function showAI(target,html){if(!target)return;target.innerHTML=html;target.style.display='block'}
async function analyzeRecipe(dataUrl,notes,target){
  showAI(target,'<b>AI is reading your recipe…</b><div class="small">Analyzing the actual image you selected.</div>');
  try{
    const r=await fetch('/api/recipe-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:dataUrl,text:notes||''})});
    const d=await r.json();
    if(!r.ok)throw new Error(d.error||'AI request failed');
    window.__lastRecipeAI={name:d.name||'Untitled recipe',ingredients:Array.isArray(d.ingredients)?d.ingredients:[],instructions:d.instructions||'',sourceNote:d.sourceNote||''};
    const list=window.__lastRecipeAI.ingredients;
    showAI(target,'<b>AI recipe recognition</b><div>'+esc(window.__lastRecipeAI.name)+'</div>'+(list.length?'<ul>'+list.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'')+(window.__lastRecipeAI.instructions?'<div class="small" style="margin-top:8px">'+esc(window.__lastRecipeAI.instructions)+'</div>':'')+(window.__lastRecipeAI.sourceNote?'<div class="small" style="margin-top:8px">'+esc(window.__lastRecipeAI.sourceNote)+'</div>':''));
    return window.__lastRecipeAI;
  }catch(e){window.__lastRecipeAI=null;showAI(target,'<b>AI could not read this image.</b><div class="small">'+esc(e.message||'Check the AI connection and try again.')+'</div>');return null}
}
function readFile(file,done){const r=new FileReader();r.onload=()=>done(r.result);r.readAsDataURL(file)}
window.captureSelected=function(){const f=document.getElementById('captureFile')?.files?.[0];if(!f)return;const p=document.getElementById('capturePreview');if(!f.type.startsWith('image/')){p.innerHTML='<div class="card">Video selected.</div>';p.style.display='block';return}readFile(f,dataUrl=>{p.innerHTML='<img src="'+dataUrl+'">';p.style.display='block';analyzeRecipe(dataUrl,document.getElementById('captureText')?.value||'',document.getElementById('captureAi'))})};
window.recipeSelected=function(){const f=document.getElementById('recipeFile')?.files?.[0];if(!f)return;readFile(f,dataUrl=>{const p=document.getElementById('recipePreview');p.innerHTML='<img src="'+dataUrl+'">';p.style.display='block';analyzeRecipe(dataUrl,document.getElementById('recipeNotes')?.value||'',document.getElementById('recipeAi')).then(d=>{if(d&&!document.getElementById('recipeName').value)document.getElementById('recipeName').value=d.name||'';if(d&&d.ingredients?.length&&!document.getElementById('recipeNotes').value)document.getElementById('recipeNotes').value=d.ingredients.join('\\n')})})};
const originalSave=window.saveModal;
window.saveModal=function(){const title=document.getElementById('mt')?.textContent;if(title!=='Quick Capture'){return originalSave.apply(this,arguments)}const text=document.getElementById('captureText')?.value.trim()||'',file=document.getElementById('captureFile')?.files?.[0];if(!text&&!file)return alert('Add a note, link, screenshot or video first.');if(file&&file.type.startsWith('image/')){readFile(file,dataUrl=>{const ai=window.__lastRecipeAI||{name:'Untitled recipe',ingredients:[],instructions:'',sourceNote:''};data.recipes.push({name:ai.name||'Untitled recipe',link:'',notes:ai.ingredients?.join('\\n')||ai.instructions||text,image:dataUrl,date:new Date().toLocaleDateString(),source:'AI Recipe Capture'});closeModal();save();show('recipes')});return}data.us.push({cat:'Inbox',text:text||'Uploaded video',date:new Date().toLocaleDateString()});closeModal();save()};
const originalOpenCapture=window.openCapture;window.openCapture=function(){window.__lastRecipeAI=null;originalOpenCapture.apply(this,arguments)};
const originalOpenRecipe=window.openRecipe;window.openRecipe=function(){window.__lastRecipeAI=null;originalOpenRecipe.apply(this,arguments)};
})();</script>`;

self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==location.origin||!(/\\/$|\\/index\\.html$/).test(u.pathname))return;e.respondWith(fetch(e.request).then(async r=>{const h=new Headers(r.headers);h.set('Cache-Control','no-store');let t=await r.text();const first=t.indexOf('<script>');if(first>=0)t=t.slice(0,first)+BOOT+t.slice(first);else t+=BOOT;t+=CAL+RECIPE_FIX+RECIPE_DESIGN+AI_RECIPE;return new Response(t,{status:r.status,statusText:r.statusText,headers:h})}).catch(()=>caches.match(e.request))) });